db/db-visualization.xml
=> The file from db.lewagon.com

Gemfile, Gemfile.lock, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20171127132043_devise_create_users.rb, db/schema.rb, test/fixtures/users.yml, test/models/user_test.rb
Guys, finished to create model User
=> done creating model User with Devise

app/controllers/treehouses_controller.rb, app/models/treehouse.rb, db/migrate/20171127133013_create_treehouses.rb, db/schema.rb, test/controllers/treehouses_controller_test.rb, test/fixtures/treehouses.yml, test/models/treehouse_test.rb
Done model and controller Treehouse
=> done creating model & controller Treehouse

config/routes.rb
added first routes of our apps..
=> created first routes

app/controllers/journeys_controller.rb, app/models/journey.rb, db/migrate/20171127135324_create_journeys.rb, test/controllers/journeys_controller_test.rb, test/fixtures/journeys.yml, test/models/journey_test.rb
=> created model Journey

app/controllers/treehouses_controller.rb, app/views/treehouses/index.html.erb, db/schema.rb
Hey guys, here are the changes:
- folder "treehouses" in /views
- add action "index" to treehouse controller
Can you validate the PR?
Thxx
=> Added index action to treehouses controller and created treehouses views folder

app/controllers/treehouses_controller.rb, app/views/treehouses/index.html.erb, db/seeds.rb
=> Fix treehouses controller

app/controllers/treehouses_controller.rb, app/views/pages/home.html.erb, app/views/shared/_form.html.erb
Added forms in the form to fetch the data in the db from the search bar
=> Form with params

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
=> centered forms of sign_in, logout and forgot_passwd

app/assets/stylesheets/components/_cabin-cards.scss, app/assets/stylesheets/components/_filters.scss, app/assets/stylesheets/components/_index.scss, app/controllers/treehouses_controller.rb, app/views/shared/_form.html.erb, app/views/treehouses/index.html.erb, db/seeds.rb
- reviewed the seeding process
- renamed the capacity into guests_number in the form on the home
- began the work on the index page of the treehouses results
@lionel-k can you check these changes ? thanks!!
=> Changes in seeds, form on the home, and treehouses results

app/assets/stylesheets/components/_message-dashboard.scss, app/views/journeys/index.html.erb, app/views/layouts/application.html.erb
squelette dashboard traveling part
=> Create squelette dashboard

app/controllers/treehouses_controller.rb, app/models/treehouse.rb, app/views/shared/_form.html.erb, app/views/treehouses/new.html.erb
=> Added form to create a new treehouse

app/assets/stylesheets/components/_index.scss, app/views/treehouses/show.html.erb
need a quick validation just a suppression of @import "treecard"
=> Delete treecard new

app/assets/stylesheets/components/_treeshow.scss, app/views/treehouses/show.html.erb
=> modal reservation request added

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/treehouses_controller.rb, app/javascript/components/select2.js, app/javascript/packs/application.js, app/views/layouts/application.html.erb, app/views/shared/_form.html.erb, package.json, yarn.lock
=> Autocomplete town

app/controllers/journeys_controller.rb, app/models/journey.rb, app/policies/journey_policy.rb, app/views/journeys/index.html.erb, app/views/layouts/application.html.erb, app/views/treehouses/index.html.erb, app/views/treehouses/show.html.erb
=> import of the total price

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_results-cards.scss, app/controllers/treehouses_controller.rb, app/models/treehouse.rb, app/uploaders/photo_uploader.rb, app/views/treehouses/index.html.erb, app/views/treehouses/new.html.erb, app/views/treehouses/show.html.erb, db/migrate/20171129112745_add_photo_to_treehouses.rb, db/schema.rb, db/seeds.rb
Added image to be stored on Cloudinary and title and description
=> Seed with img cloudinary

app/javascript/packs/application.js
=> remove map from applicationjs

app/javascript/packs/application.js, app/javascript/totalPrice.js, app/models/journey.rb, app/views/journeys/index.html.erb, app/views/shared/_navbar.html.erb, app/views/treehouses/index.html.erb, app/views/treehouses/show.html.erb, db/schema.rb
=> Total price

app/assets/stylesheets/components/_results-bar.scss, app/views/layouts/application.html.erb
Change footer in index page of treehouses
=> change footer to show page

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/controllers/treehouses_controller.rb, app/views/treehouses/new.html.erb
=> Optimize form new treehouse

app/assets/stylesheets/components/_treeshow.scss, app/views/treehouses/show.html.erb
=> Improve show

app/assets/stylesheets/components/_navbar.scss
=> logo resize

app/assets/stylesheets/components/_treeshow.scss, app/javascript/totalPrice.js, app/views/treehouses/show.html.erb
=> Automatic price

app/controllers/treehouses_controller.rb, app/javascript/packs/map.js, app/javascript/totalPrice.js, app/views/treehouses/_map_box.html.erb
=> Custom markers

app/assets/stylesheets/components/_message-dashboard.scss, app/assets/stylesheets/components/_tabs-dashboard.scss, app/assets/stylesheets/pages/_dashboard.scss, app/javascript/components/tabs.js, app/javascript/packs/application.js, app/views/journeys/index.html.erb
=> dashboard js ready

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_results-bar.scss, app/assets/stylesheets/components/_results-cards.scss, app/views/pages/home.html.erb, app/views/shared/_form.html.erb, app/views/shared/_form_index.html.erb, app/views/treehouses/index.html.erb
Can you validate these css improvements guys?
Thanks :)
=> Improve css home index

app/assets/stylesheets/components/_message-dashboard.scss, app/assets/stylesheets/components/_tabs-dashboard.scss, app/assets/stylesheets/pages/_dashboard.scss, app/views/journeys/index.html.erb
=> dashboard close to finish
